name: Train and Deploy MRI Model

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "production"
                type: choice
                options:
                    - production

jobs:
    train-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python Environment and Install Requirements
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd ~/projects/ProjetML
                      if [ ! -d "venv" ]; then
                        python3.10 -m venv venv
                      fi
                      source venv/bin/activate
                      pip install --upgrade pip
                      pip install -r requirements.txt

            - name: Train Model
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd ~/projects/ProjetML
                      source venv/bin/activate
                      python train_models.py

            - name: Restart Streamlit Service
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                    sudo /bin/systemctl restart streamlit
                    sudo /bin/systemctl status streamlit --no-pager
